### ISSUE TITLE
Implement ISigningKeyService

### ISSUE THREAD

**Issue by omerlh** [MattCotterellNZ/IdentityServer3.Contrib.AzureKeyVaultTokenSigningService#7]
Hey
I am facing the same problem you are - trying to decide between CloudHSM and Azure KeyVault as the store for the private key. I saw the work you did, and it look like a great start, but the main thing that missing here, and that I am not sure how to implement is the `ISigningKeyService`. The main problem is the dependency in `X509Certificate2`. Look like you can [generate](http://www.wiktorzychla.com/2012/12/how-to-create-x509certificate2.html) a `X509Certificate2` from 'JsonWebKey' (which is what you can export from the key vault, as far as I know) but this look like very ugly code to me.
I was wondering if you have any thought regarding this problem.
Thanks,
Omer

**Comment by omerlh** [comment]
I've also opened an issue in identity server repo: IdentityServer/IdentityServer3#2727

**Comment by MattCotterellNZ** [comment]
I'm not sure how to resolve this one myself. I think you're right: on startup, we fetch the public key from Key Vault, use it to build an `X509Certificate2` instance and pass it back to IdentityServer3/4 that way, but seeing as a public key != a certificate, it would be rather messy. I'll poke around the `X509Certificate2` implementation in .NET and see what I can do. Watch this space :)

**Comment by omerlh** [comment]
I am working on it myself right now, it is not easy and the code is pretty much a mess. It is also very ugly because of the dependency between the `ITokenSigningService` and `ISigningKeyService` - especially the need to use the same kid. If I will have something that I feel good with, I will share it...

**Comment by MattCotterellNZ** [comment]
Sounds awesome. I do apologize if my code seems in a bit of a state, it's still very much a work in progress at this stage. Let me know if it gets in the way and I'll do what I can to help out.

**Comment by omerlh** [comment]
This is really fine :) I thought that's the situation...
 I am also facing the same problem right now, so I might contribute some PR. My main problem is that I am looking for a generic solution that will allow me to switch between keyvault and PKCS11 easily.

**Comment by MattCotterellNZ** [comment]
Here's hoping your solution in https://github.com/IdentityServer/IdentityServer3/pull/2732 goes through, it looks like this would solve a lot of our problems. Frankly, I've spent the past three hours banging my head against the IdentityServer, .NET and Key Vault APIs and I cannot see a clean way to do this beyond just changing IdentityServer to be more friendly with JWKs instead of requiring X509s.

**Comment by omerlh** [comment]
I was thinking the same, there is a way but the code become so ugly that I preferred to propose a PR to identity server and hope it will be accepted...

**Comment by omerlh** [comment]
Hey,
I've published a [small adapter](https://github.com/Soluto/IdentityServer.Contrib.JsonWebKeyAdapter) as a nuget package. This might help you with this...

**Comment by MattCotterellNZ** [comment]
Oh, that looks fantastic! I'll get to work on using this soon.

**Comment by omerlh** [comment]
Thank you! Hope it will be usefull :)
